language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: jeffrey.jagoda@gmail.com
  api_key:
    secure: wIA4Wd1UcGL7juWp8SlGTe0tPKAMR1+xAf14mblGlqQXhBr/0H8Y1pOrE34UHoRKXtsDGV9Igq2BJPl/H2njBalaSZzeRiEZ37D0c1WjuRxFIfep+1WB7+bNGYsS9lou/eI2zp5+y52zfLPQXbDJfAFYvp45FnVDm0PF6UKAg6E=
  on:
    tags: true
    repo: jagoda/outflux
    all_branches: true
