language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: jeffrey.jagoda@gmail.com
  api_key:
    secure: Td5ljwviTVwb/WoTb/QeiLkKWwyTxNrCdfUJEnogox7lu9kbDxT3AIB5VlYxxYffiwMfI00vwYQN5bahc4paXyPxSt8L3hyOtVZgLERgjlbiwc9iqOhtpbnsymW9RzcXcI8KUzjyz0CAKR9rJumgzqqxDO7fsMNY+mprNQR0ucg=
  on:
    tags: true
    repo: jagoda/outflux
    all_branches: true
